services:
  fileshare:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fileshare_app
    ports:
      - "18080:8080"
    environment:
      FILESHARE_USERNAME: scoob
      FILESHARE_PASSWORD: choom
      FILESHARE_ROOT: /data/files
      ASPNETCORE_URLS: http://+:8080
    volumes:
      - ./shared-files:/data/files
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: fileshare_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN_FILESHARE}
    depends_on:
      - fileshare
